In [1]:
import numpy as np
array_1d = np.array([1,2,3]) # it is similar to a list
array_1d


array([1, 2, 3])

In [2]:
# 2D arrays
array_2d = np.array([(1,2,3), (4,5,6)]) # Similar to a table
array_2d


array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 3D array
array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #similar to two tables
array_3d


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [4]:
#Creating an array filled with zeros

np.zeros((3,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
# Creating an array filled with ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
# And this creates an array of a desginated shape that is pre filled with a specific value

np.full((5,3),8)


array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [7]:
# ndarray.flatten() returns a copy of the array collapsed into one dimension

array_2d = np.array([(1,2,3), (4,5,6)])
print(array_2d)
print()
array_2d.flatten()

[[1 2 3]
 [4 5 6]]



array([1, 2, 3, 4, 5, 6])

In [11]:
# narray.reshape() gives a new shape to an array without changng its data
array_2d = np.array([(1,2,3), (4,5,6)])
print(array_2d)
print()
array_2d.reshape(3,2)


[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# Adding a value of -1 in the desginated new shape makes the process more efficient, as it indicates for NumPy to 
# automatically infer the value based on other given values

array_2d = np.array([(1,2,3),(4,5,6)])
print(array_2d)
print()
array_2d.reshape(3,-1)


[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# ndarray.tolist()
# this converts an array to a list object. multidimensional arrays are conerted to nested lists

array_2d - np.array([(1,2,3), (4,5,6)])
print(array_2d)
print()
array_2d.tolist()


[[1 2 3]
 [4 5 6]]



[[1, 2, 3], [4, 5, 6]]

In [13]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a.max())
print(a.mean())
print(a.min())
print(a.std())

[[1 2 3]
 [4 5 6]]

6
3.5
1
1.707825127659933


In [14]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()

print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)

[[1 2 3]
 [4 5 6]]

(2, 3)
int64
6
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
Slicing may also be used to access subarrays of a NumPy array:


In [15]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

a[:, 1:]

[[1 2 3]
 [4 5 6]]



array([[2, 3],
       [5, 6]])

In [16]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([[1, 2, 3], [1, 2, 3]])
print('a:')
print(a)
print()
print('b:')
print(b)
print()
print('a + b:')
print(a + b)
print()
print('a * b:')
print(a * b)

a:
[[1 2 3]
 [4 5 6]]

b:
[[1 2 3]
 [1 2 3]]

a + b:
[[2 4 6]
 [5 7 9]]

a * b:
[[ 1  4  9]
 [ 4 10 18]]


In [18]:
a = np.array([(1, 2), (3, 4)])
print(a)
print()

a[1][1] = 100
a

[[1 2]
 [3 4]]



array([[  1,   2],
       [  3, 100]])

In [ ]:
However, the array cannot be lengthened or shortened:

In [19]:
a = np.array([1, 2, 3])
print(a)
print()

a[3] = 100
a

[1 2 3]



IndexError: index 3 is out of bounds for axis 0 with size 3